
services:
  mediasoup-server:
    build: .
    platform: linux/amd64
    network_mode: host
    environment:
      - PORT=3000
    # ports:
    #   - "3000:3000"
      # - "40000-49999"
    restart: unless-stopped