query fetchOrderForDriverNew2(
  $state: [task_state_enum!]
  $limit: Int
  $offset: Int
  $driver_vehicle_id: uuid
  $start_date: timestamp
  $end_date: timestamp
) {
  task(
    where: {
      is_active: {_eq: true}
      state: {_nin: $state}
      driver_vehicle_id: {_eq: $driver_vehicle_id}
      estimate_delivery_date: {_gte: $start_date, _lte: $end_date}
    }
    limit: $limit
    offset: $offset
    order_by: {rank_id: asc}
  ) {
    state
    id
    is_enable_buddycan_flow
    customer_order {
      order_code
      id
      delivery_fee
      delivery_preference
      description
      order_date
      name
      is_prepaid
      is_active
      organizationAddressByShippingAddressId {
        name
        address_line1
        address_line2
        location
      }
      organization_user {
        organization {
          name
          is_credit_available
        }
        user {
          first_name
          last_name
        }
      }
      customer_order_items {
        actual_delivery_date
        estimate_delivery_date
        qty
        unit_price
        id
        product_variation_id
        service_tax
        product_variation {
          price
          product {
            name
          }
        }
      }
      customer_order_customer_assets {
        quantity_dispensed
        quantity_requested
        customer_asset {
          id
          name
          description
          registration_number
        }
      }
    }
    fillup_requests {
      id
      quantity
      driver_vehicle {
        vehicle {
          registration_number
        }
      }
    }
    organization_address {
      address_line1
      address_line2
      pincode
    }
  }
}
