query fetchOrderForDriverNew2(
  $state: [task_state_enum!]
  $limit: Int
  $offset: Int
  $driver_vehicle_id: uuid
  $start_date: timestamp
  $end_date: timestamp
) {
  task(
    where: {
      is_active: {_eq: true}
      state: {_nin: $state}
      driver_vehicle_id: {_eq: $driver_vehicle_id}
      estimate_delivery_date: {_gte: $start_date, _lte: $end_date}
    }
    limit: $limit
    offset: $offset
    order_by: {rank_id: asc}
  ) {
    state
    category
    id
    driver_vehicle_id
    driver_vehicle {
      id
      driver_id
      is_active
      user {
        first_name
        last_name
        phone_number
      }
      vehicle {
        id
        name
        registration_number
        category
        model
        fuel_tank_capacity
        vehicle_devices(
          offset: 0
          limit: 1
          order_by: {created_at: desc}
          where: {is_active: {_eq: true}}
        ) {
          device_id
        }
      }
    }
    customer_order {
      id
      order_code
      state
      is_otp_required
      organizationAddressByShippingAddressId {
        name
        location
        address_line1
        address_line2
      }
      organization_user {
        organization {
          name
        }
        user {
          first_name
          last_name
          phone_number
          delivery_otp
        }
      }
      customer_order_items {
        task {
          task_values {
            quantity_dispensed
            customer_asset {
              name
            }
          }
        }
        actual_qty
        amount
        qty
        estimate_delivery_date
        actual_delivery_date
        product_variation {
          product {
            name
          }
        }
      }
      customer_order_customer_assets {
        quantity_dispensed
        quantity_requested
        customer_asset {
          name
        }
      }
    }
    fillup_requests {
      fuel_request_type
      id
      quantity_approved
      quantity
      state
      vehicle_tank_type_product_variation {
        product_variation {
          product {
            name
          }
        }
      }
    }
    is_enable_buddycan_flow
    organization_address {
      location
      address_line1
    }
  }
}
