query fetchAddressByName( $address_type: address_type_enum,$organization_user_id: uuid, $name: String) {
  organization_address(
    where: {
      address_type: {_eq: $address_type}
      organization_user_id: {_eq: $organization_user_id}
      is_active: {_eq: true}
      _or: [
        {house_number: {_ilike: $name}}
        {address_line1: {_ilike: $name}}
        {address_line2: {_ilike: $name}}
        {pincode: {_ilike: $name}}
      ]
    }
  ) {
    address_line1
    address_line2
    house_number
    organization_address_payment_methods {
      customer_payment_method {
        id
        name
        value
      }
    }
    city {
      id
      name
      state_id
    }
    city_id
    country {
      id
      name
    }
    country_id
    house_number
    id
    organization_address_payment_methods {
      customer_payment_method {
        id
        name
        value
      }
    }
    is_active
    localities_id
    location
    name
    organization_user_id
    pincode
    state_id
    street_address
    address_type
    state {
      country_id
      id
      code
      name
      numeric_code_id
    }
  }
}
