mutation createNewBusinessOrganization($object: addCustomerAppUserLeadToErpInput!) {
  addCustomerAppUserLeadToErp(object: $object) {
    id
    is_active
    organization_erp_code
  }
}

# {
#   "object": {
#     "is_owner": true,
#     "is_active": true,
#     "user_id": "",
#     "organization": {
#       "data": {
#         "brand": "",
#         "brand_logo": "",
#         "cin_number": "",
#         "default_currency": "",
#         "gst_number": "",
#         "head_office_general_email": "",
#         "head_office_general_phone_number": "",
#         "holding_company": true,
#         "holding_company_name": "",
#         "invoice_email": "cvcvg@gmail.com",
#         "is_active": true,
#         "invoices_uploaded": true,
#         "is_bussiness": true,
#         "is_post_paid": false,
#         "name":  "org name",
#         "pan_number": "",
#         "signed_invoice_on_email": true,
#         "technical_contact_email": "",
#         "website_url": "",
#         "technical_contact_phone_number": "",
#         "technical_contact_full_name": ""
#       }}}
# }
