query fetchOrganizationSegmentation {
  organization_segmentation(
    # distinct_on: id
    limit: 50
    offset: 0
    order_by: {rank_id: asc}
  ) {
    id
    is_active
    name
    sku
    rank_id
  }
}

# organization_segmentation_id
# {
#             "is_active": true,
#             "is_owner": false,
#             "organization": {
#                 "data": {
#                     "brand": "testbusiness",
#                     "brand_logo": "yyr",
#                     "cin_number": "asdasd67",
#                     "default_currency": "b8b0753d-df29-42c3-a7af-bb5a212a7600",
#                     "gst_number": "asdsa",
#                     "head_office_general_email": "asd@sad.com",
#                     "head_office_general_phone_number": "",
#                     "holding_company": false,
#                     "holding_company_name": "test",
#                     "invoice_email": "asd@sad.com",
#                     "invoices_uploaded": true,
#                     "is_active": true,
#                     "is_bussiness": true,
#                     "is_post_paid": false,
#                     "name": "testbusiness",
#                     "pan_number": "asdas",
#                     "signed_invoice_on_email": true,
#                     "technical_contact_email": "asd@sad.com",
#                     "technical_contact_full_name": "testb",
#                     "technical_contact_phone_number": "9910381909",
#                     "website_url": "www.sad.com",
#                     "organization_segmentation_id": "6bc628e0-726a-477f-b2b3-6cb2423ee1c5"
#                 }
#             },
#             "user_id": "55fccf89-f104-446a-841f-0c23f988435d"
#         }
