query fetchUserProfile {
  user(
    where: {
      organization_users: {
        is_owner: {_eq: true}
        organization: {is_business: {_eq: false}}
      }
    }
  ) {
    id
    first_name
    last_name
    middle_name
    description
    delivery_otp
    phone_number
    email
    pan_number
    profile_pic
    referral_code
    customer_segmentation {
      id
      name
    }
    organization_users {
      id
      is_owner
      organization_user_type
      organization {
        is_business
        cin_number
        brand
        brand_logo
        name
        is_post_paid
        is_active
        id
        default_currency
        pan_number
        description
        gst_number
        holding_company
        signed_invoice_on_email
        technical_contact_email
        technical_contact_full_name
        technical_contact_phone_number
      }
      user {
        email
        middle_name
        last_name
        pan_number
        phone_number
        first_name
        is_active
      }
    }
  }
}
